permalink: /:categories/:year:month:day/:title
url: http://127.0.0.1:4000
baseurl: 

# variables
name: boobo94
description: About me
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

social:
  stackoverflow:
    icon: fab fa-stack-overflow
    link: https://stackoverflow.com/users/4471897/bogdan-alexandru-militaru?tab=profile
  facebook:
    icon: fab fa-facebook
    link: https://www.facebook.com/bogdanalexandru.militaru
  linkedin:
    icon: fab fa-linkedin
    link: https://www.linkedin.com/in/bogdan-alexandru-militaru-bb801697/
  github:
    icon: fab fa-github
    link: https://github.com/boobo94
  skype:
    icon: fab fa-skype
    link: https://join.skype.com/dU90XfWbX19q
  mail:
    icon: fas fa-envelope
    link: mailto:mba@cmevo.com
  feed:
    icon: fa fa-rss-square
    link: /feed.xml

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
